#!/bin/sh

# Draws a progress bar based on % of song complete via mpris

PLAYED_CHAR="━"
UNPLAYED_CHAR="─"
COL_WIDTH="26"

LENGTH=$(playerctl metadata | grep "mpris:length " | xargs -0  echo -e | cut -d" " -f16-)
POS=$(playerctl position)
PROGRESS=$(echo "scale=2;$POS / ($LENGTH  / 1000000)" | bc -l)
# PROGRESS_PERCENT=$(echo "$PROGRESS * 100" | bc -l)

PLAYED_NUM_CHARS=$(echo "$COL_WIDTH * $PROGRESS" | bc)
UNPLAYED_NUM_CHARS=$(echo "$COL_WIDTH - $PLAYED_NUM_CHARS" | bc)

for i in $(seq 1 $PLAYED_NUM_CHARS); do echo -n "$PLAYED_CHAR"; done
for i in $(seq 1 $UNPLAYED_NUM_CHARS); do echo -n "$UNPLAYED_CHAR"; done
